-- Initial hosted-tier schema.
--
-- No column holds a plaintext Bambu Cloud token. `webhook_url` is a bearer
-- credential and `device_ids` contains printer identifiers; neither value may
-- ever be written to a log.

CREATE TABLE accounts (
  -- This id is generated by us and is authenticated as the token ciphertext's
  -- AES-GCM additional data. It must be unguessable and must never be reused,
  -- even after this row has been deleted.
  id text PRIMARY KEY,

  -- The supported regions have different Bambu Cloud hosts. Rejecting any
  -- other value prevents an account from being sent to an unintended host.
  region text NOT NULL,
  -- Keep the supported-region set in the schema so application drift fails
  -- closed instead of silently choosing an endpoint.
  CONSTRAINT accounts_region_supported CHECK (region IN ('global', 'china')),

  -- The key id permits gradual key rotation while old rows remain decryptable.
  token_key_id text NOT NULL,
  -- A fresh base64-encoded AES-GCM nonce is stored with each ciphertext.
  token_nonce text NOT NULL,
  -- This is authenticated ciphertext with its GCM tag, never plaintext.
  token_ciphertext text NOT NULL,

  -- Printer ids are identifiers. An array keeps one account operation atomic
  -- and preserves the user's chosen order without another credential-bearing table.
  device_ids text[] NOT NULL,
  -- The TRMNL webhook URL is itself a bearer credential.
  webhook_url text NOT NULL,

  -- Rate and size ceilings are per account because TRMNL plans differ.
  max_pushes_per_hour integer NOT NULL,
  -- A non-positive budget would make scheduler behavior nonsensical.
  CONSTRAINT accounts_positive_push_budget CHECK (max_pushes_per_hour > 0),
  max_payload_bytes integer NOT NULL,
  -- Payload shedding requires a meaningful positive byte ceiling.
  CONSTRAINT accounts_positive_payload_budget CHECK (max_payload_bytes > 0),

  -- Job names can disclose private model names, so exporting them is opt-in.
  export_job_name boolean NOT NULL DEFAULT false,
  -- A refused token is not retried until explicit reauthentication replaces it.
  reauth_required boolean NOT NULL DEFAULT false,
  -- Creation time is retained for operations and stable tie-breaking only.
  created_at timestamptz NOT NULL DEFAULT now(),
  -- Null means never serviced. Each claim advances this before network work so
  -- one crashing account cannot remain permanently first in the queue.
  last_serviced_at timestamptz
);

CREATE TABLE push_records (
  -- One durable scheduler record belongs to one account. The cascade makes
  -- actual deletion a schema property rather than a second statement callers
  -- can forget, and prevents token-adjacent scheduling tombstones.
  account_id text PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
  -- Epoch milliseconds in the trailing rate-limit window. bigint avoids the
  -- 2038 boundary and an array makes pruning plus replacement one atomic write.
  recent_pushes bigint[] NOT NULL DEFAULT '{}',
  -- Null means no successful push yet; the exact previous body enables change detection.
  last_serialized text,
  -- Epoch milliseconds of the last accepted push, or null before the first one.
  last_pushed_at bigint
);

-- The partial index contains only serviceable accounts and directly supports
-- oldest-serviced-first claims, including never-serviced accounts before all others.
CREATE INDEX accounts_due_idx
  ON accounts (last_serviced_at ASC NULLS FIRST)
  WHERE reauth_required = false;
