-- Initial hosted-tier schema.
--
-- Revised before first use because the hosted tier changed from pushing to
-- TRMNL to being polled by it; no database ever contained the superseded push
-- columns or table, so recording their creation and removal would be archaeology.
-- It was revised again before first use to bind each account to its hosted
-- identity; no database ever lacked `owner_tag`, so a follow-up ALTER would
-- likewise be archaeology. No column holds a plaintext Bambu Cloud token or a
-- live screen key, and `device_ids` contains printer identifiers that must never
-- be written to a log.

CREATE TABLE accounts (
  -- This id is generated by us and is authenticated as the token ciphertext's
  -- AES-GCM additional data. It must be unguessable and must never be reused,
  -- even after this row has been deleted.
  id text PRIMARY KEY,

  -- This is a keyed HMAC of the identity provider's subject, never the subject.
  -- UNIQUE makes one signed-in person one account. It is an identifier and must
  -- never be written to a log.
  owner_tag text NOT NULL UNIQUE,

  -- The supported regions have different Bambu Cloud hosts. Rejecting any
  -- other value prevents an account from being sent to an unintended host.
  region text NOT NULL,
  -- Keep the supported-region set in the schema so application drift fails
  -- closed instead of silently choosing an endpoint.
  CONSTRAINT accounts_region_supported CHECK (region IN ('global', 'china')),

  -- The key id permits gradual key rotation while old rows remain decryptable.
  token_key_id text NOT NULL,
  -- A fresh base64-encoded AES-GCM nonce is stored with each ciphertext.
  token_nonce text NOT NULL,
  -- This is authenticated ciphertext with its GCM tag, never plaintext.
  token_ciphertext text NOT NULL,

  -- This is a SHA-256 hex digest, not the bearer key. The key is shown once and
  -- never stored. UNIQUE turns the vanishingly unlikely collision into a
  -- database error instead of allowing one user to read another user's screen.
  screen_key_fingerprint text NOT NULL UNIQUE,

  -- Printer ids are identifiers. An array keeps one account operation atomic
  -- and preserves the user's chosen order without another identifier-bearing table.
  device_ids text[] NOT NULL,

  max_payload_bytes integer NOT NULL,
  -- Payload shedding requires a meaningful positive byte ceiling.
  CONSTRAINT accounts_positive_payload_budget CHECK (max_payload_bytes > 0),

  -- Job names can disclose private model names, so exporting them is opt-in.
  export_job_name boolean NOT NULL DEFAULT false,
  -- A refused token is not retried until explicit reauthentication replaces it.
  reauth_required boolean NOT NULL DEFAULT false,
  -- Creation time is retained for operations and stable tie-breaking only.
  created_at timestamptz NOT NULL DEFAULT now(),
  -- Null means never serviced. Each claim advances this before network work so
  -- one crashing account cannot remain permanently first in the queue.
  last_serviced_at timestamptz
);

CREATE TABLE screens (
  -- One rendered screen belongs to one account. The cascade makes AGENTS.md's
  -- actual-deletion obligation a schema property rather than a second statement
  -- callers must remember, and prevents a payload tombstone after account deletion.
  account_id text PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
  -- Exact JSON served to TRMNL, with merge variables at the root.
  body text NOT NULL,
  -- Epoch milliseconds when the cron rendered this body.
  rendered_at bigint NOT NULL
);

-- The partial index contains only serviceable accounts and directly supports
-- oldest-serviced-first claims, including never-serviced accounts before all others.
CREATE INDEX accounts_due_idx
  ON accounts (last_serviced_at ASC NULLS FIRST)
  WHERE reauth_required = false;

-- PostgreSQL creates a unique B-tree index for the UNIQUE constraint on
-- screen_key_fingerprint, so a second explicit lookup index would be redundant.
